#!/usr/bin/env python3

import sys
from command.submit import submit
from command import standards


def main():

    commands = {
        'submit': submit,
        'standards': standards.graph,
        'standardsp': standards.graph_progression
    }

    if len(sys.argv) != 2:
        print_usage()
        exit()

    arg = sys.argv[1]

    if arg in commands:
        commands[arg]()
    else:
        print_usage()
        exit()

def print_usage():
    print('Usage: {} [command]'.format(sys.argv[0]))

main()
